### ISSUE TITLE
what this mean?

### ISSUE THREAD

**Issue by onion0835** [Mix-Anik/chatgpt-lib#2]
ERROR: ChatGPT failed to respond due to :AxiosError: Request failed with status code 401
/home/chatgpt/chatgpt-api/node_modules/chatgpt-lib/index.js:60
        response = response.data.split('\n\n');
                                 ^

TypeError: Cannot read properties of undefined (reading 'split')
    at ChatGPT.ask (/home/chatgpt/chatgpt-api/node_modules/chatgpt-lib/index.js:60:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPT.initCliConversation (/home/chatgpt/chatgpt-api/node_modules/chatgpt-lib/index.js:128:28)

**Comment by Mix-Anik** [comment]
It seems there is a bug regarding how errors are handled currently. thanks for letting know, will look into it.
